name: Update Big Basket Sheet Daily

on:
  schedule:
    - cron: "30 0 * * *"  # Runs daily at 6:00 AM IST
  workflow_dispatch:      # Allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GSHEET_SECRET: ${{ secrets.GSHEET_SECRET }}   # Add your new secret here
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          # If you need to save GSHEET_SECRET to a file or export it:
          # echo "$GSHEET_SECRET" > gsheet_secret.txt
          # export GSHEET_SECRET="$GSHEET_SECRET"

      - name: Run BigBasket Script
        env:
          GSHEET_SECRET: ${{ secrets.GSHEET_SECRET }}   # Pass it to your script environment if needed
        run: python bigbasket.py
